# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'patientview' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#  use_frameworks!

  # Pods for patientview

	pod 'Fabric'
	pod 'Crashlytics'
    pod 'SwiftyJSON', '3.1.4'
    pod 'Charts', '3.0.1'
    pod 'Firebase/Messaging', '~> 5.15.0'
    pod 'Firebase/Core', '~> 5.15.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
